### ISSUE TITLE
Project completion

### ISSUE THREAD

**Issue by khadem-test** [khadem-mh/todoLIist#1]
Hi, 
Your **project** is visually beautiful and also responsive, but it seems that the project is not yet finished and its logic has not been defined?
When will the project end?
![99399728-0d096d00-290c-11eb-9ee5-59cc8358676c](https://github.com/khadem-mh/todoLIist/assets/165303170/babd610a-4760-49d3-94e7-fa734bc18673)
I think you can use this photo as well

**Comment by khadem-mh** [comment]
Thank you for your patience and your opinion the project is not clear when it will end, but I will try to finish faster.
